config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
        @tweets = Tweet.all
    end
    def new
        @tweet = Tweet.new
    end
    def create
        message = params[:tweet][:message]
        tdate = params[:tweet][:tdate]
        @tweet = Tweet.new(message: message, tdate: tdate)
        if @tweet.save
            flash[:notice] = "ツイートしました！"
            redirect_to root_path
        else
            flash[:failed] = "ツイートに失敗しました。"
            render 'new'
        end
    end
    def show
        @tweet = Tweet.find(params[:id])
    end
    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
            flash[:destroy] = "ツイートを削除しました。"
        redirect_to root_path, flash: {destroy:  "ツイートを削除しました。"}

    end
    def edit
         @tweet = Tweet.find(params[:id])
    end
    def update
        @tweet = Tweet.find(params[:id])
        @tweet.update(message: params[:tweet][:message],tdate: params[:tweet][:tdate])
        if @tweet.save
            flash[:update] = "更新しました！"
            redirect_to root_path
        else
            flash[:fail] = "更新に失敗しました。"
            render 'edit'
        end
    end
end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div id="container">
      <div id="header">
        <%= render "header" %> 
      </div>
      <div id="sidebar">
        <%= render "sidebar" %>
      </div>
      <div id="content">
        <%= yield %>
      </div>
      <div id="footer">
        <%= render "footer" %>
      </div>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<% if flash[:failed] %>
  <p><font color="red"><%= flash[:failed] %></font></p>
  <% end %>
  <% if flash[:fail] %>
  <p><font color="red"><%= flash[:fail] %></font></p>
  <% end %>
<%= form_for @tweet do |form| %>
  

  <div class="field">
 
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_header.html.erb
<img  id="header_img" src="assets/header.jpg">

app/views/tweets/_sidebar.html.erb
<img src="assets/icon.png">
<div id="side">
 <p>ポケモントレーナーX</p>
 <p id="s"><%= link_to 'ツイート', new_tweet_path %></p>    
</div>

app/views/tweets/edit.html.erb
<h3>Editing tweet</h3>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<% require 'date' %>

<h3>ツイート</h3>
<% if flash[:notice] %>
  <p><font color="green"><%= flash[:notice] %></font></p>
<% end %>  
<% if flash[:update] %>
  <p><font color="green"><%= flash[:update] %></font></p>
<% end %>
<% if flash[:destroy] %>
  <p><font color="blue"><%= flash[:destroy] %></font></p>
<% end %>
<table>
    <tbody>
<% @tweets.each do |tweet| %>
  <tr>
     <td><img  id="a" src="assets/icon.png"></td>
     <td id="b"><%= tweet.message %></td>
     <td><%= link_to 'show', tweet %>
     <%= link_to 'delete', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
     <%= link_to 'edit', edit_tweet_path(tweet) %></td>
     <% tweet.tdate = tweet.created_at %>
     <% t1 = tweet.tdate %>
     <% t2 = Time.current %>
     
     <% if (t2 - t1) <= 60 * 60 %>
       <td><%= ((t2 - t1) / 60).to_i.to_s %> 分前 </td>
     <% elsif (t2 - t1) <= 60 * 60 * 24 %>
       <td><%= ((t2 - t1) / 3600).to_i.to_s %>時間前</td>
     <% else %>
       <td><%= (t2.to_date - t1.to_date).to_i.to_s %>日前</td>
     <% end %>

  </tr>

<% end %> 
    </tbody>
</table>

app/views/tweets/new.html.erb
<h3>New Tweet</h3>
<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h3>tweet</h3>

  <p>
     <%= @tweet.message %>
    
  </p>
     
 
<%= link_to 'Back', '/' %>